from __future__ import annotations

import argparse
from dataclasses import dataclass
from pathlib import Path
from typing import Any

from .config import build_config, validate_dispatch_config
from .env import load_dotenv
from .errors import SymphonyError
from .logging import StructuredLogger
from .models import Issue
from .tracker import LinearClient
from .workflow import load_workflow


LINEAR_STATE_PATH = Path("docs/linear-state.md")
PLANS_PATH = Path("docs/plans.md")
SYNC_MARKER = "<!-- symphony-linear-sync -->"


@dataclass(frozen=True)
class PlanMilestone:
    number: str
    title: str
    linear_identifier: str
    status: str
    body: str


class DocsLinearSync:
    def __init__(
        self,
        repo_root: Path,
        tracker: Any,
        *,
        logger: StructuredLogger | None = None,
        plans_path: Path = PLANS_PATH,
        linear_state_path: Path = LINEAR_STATE_PATH,
    ) -> None:
        self.repo_root = repo_root
        self.tracker = tracker
        self.logger = logger or StructuredLogger()
        self.plans_path = repo_root / plans_path
        self.linear_state_path = repo_root / linear_state_path

    def sync(self, *, pull: bool = True, push: bool = True) -> None:
        milestones = parse_plan_milestones(self.plans_path.read_text(encoding="utf-8"))
        issues = self.tracker.fetch_project_issues()
        issues_by_identifier = {issue.identifier: issue for issue in issues}

        if pull:
            self._write_linear_state(issues)
            self._update_plan_statuses(milestones, issues_by_identifier)

        if push:
            for milestone in milestones:
                issue = issues_by_identifier.get(milestone.linear_identifier)
                if issue is None:
                    self.logger.event(
                        "linear_sync_issue_missing",
                        "error",
                        issue_identifier=milestone.linear_identifier,
                    )
                    continue
                description = render_issue_description(milestone)
                self.tracker.update_issue_description(issue.id, description)
                self.logger.event(
                    "linear_issue_synced_from_docs",
                    issue_id=issue.id,
                    issue_identifier=issue.identifier,
                )

    def _write_linear_state(self, issues: list[Issue]) -> None:
        self.linear_state_path.write_text(render_linear_state(issues), encoding="utf-8")
        self.logger.event("linear_state_written", path=str(self.linear_state_path))

    def _update_plan_statuses(
        self,
        milestones: list[PlanMilestone],
        issues_by_identifier: dict[str, Issue],
    ) -> None:
        text = self.plans_path.read_text(encoding="utf-8")
        updated = text
        for milestone in milestones:
            issue = issues_by_identifier.get(milestone.linear_identifier)
            if issue is None:
                continue
            status = status_from_linear_state(issue.state)
            section = _find_milestone_section(updated, milestone.number, milestone.title)
            if section is None:
                continue
            start, end = section
            body = updated[start:end]
            replaced = _replace_status_line(body, status)
            updated = updated[:start] + replaced + updated[end:]
        if updated != text:
            self.plans_path.write_text(updated, encoding="utf-8")
            self.logger.event("plans_statuses_updated", path=str(self.plans_path))


def parse_plan_milestones(text: str) -> list[PlanMilestone]:
    headings = list(_iter_milestone_headings(text))
    milestones: list[PlanMilestone] = []
    for index, (start, number, title) in enumerate(headings):
        end = _milestone_section_end(text, start, headings[index + 1][0] if index + 1 < len(headings) else len(text))
        body = text[start:end]
        linear_identifier = _extract_field(body, "Linear")
        if not linear_identifier:
            continue
        milestones.append(
            PlanMilestone(
                number=number,
                title=title,
                linear_identifier=linear_identifier,
                status=_extract_field(body, "Status") or "",
                body=body.strip(),
            )
        )
    return milestones


def render_issue_description(milestone: PlanMilestone) -> str:
    return (
        f"{SYNC_MARKER}\n"
        f"Synced from `docs/plans.md` milestone {milestone.number}.\n\n"
        f"{milestone.body}\n"
    )


def render_linear_state(issues: list[Issue]) -> str:
    rows = sorted(issues, key=lambda issue: issue.identifier)
    lines = [
        "# Linear State",
        "",
        "Generated by `symphony docs-sync`. Do not edit by hand.",
        "",
        "| Issue | State | Priority | Title |",
        "| --- | --- | ---: | --- |",
    ]
    for issue in rows:
        priority = "" if issue.priority is None else str(issue.priority)
        title = _escape_table(issue.title)
        if issue.url:
            identifier = f"[{issue.identifier}]({issue.url})"
        else:
            identifier = issue.identifier
        lines.append(f"| {identifier} | {issue.state} | {priority} | {title} |")
    lines.append("")
    return "\n".join(lines)


def status_from_linear_state(state: str) -> str:
    key = state.strip().lower()
    if key == "done":
        return "implemented."
    if key in {"canceled", "cancelled", "duplicate"}:
        return f"{key}."
    if key == "in progress":
        return "in progress."
    return "planned."


def main(argv: list[str] | None = None) -> int:
    parser = argparse.ArgumentParser(description="Sync project docs with Linear.")
    parser.add_argument(
        "workflow",
        nargs="?",
        type=Path,
        help="path to WORKFLOW.md; defaults to ./WORKFLOW.md",
    )
    parser.add_argument("--pull-only", action="store_true", help="write docs from Linear only")
    parser.add_argument("--push-only", action="store_true", help="write Linear from docs only")
    args = parser.parse_args(argv)

    logger = StructuredLogger()
    try:
        load_dotenv(args.workflow or Path.cwd())
        workflow = load_workflow(args.workflow)
        config = build_config(workflow)
        validate_dispatch_config(config)
        sync = DocsLinearSync(workflow.path.parent, LinearClient(config), logger=logger)
        sync.sync(pull=not args.push_only, push=not args.pull_only)
        return 0
    except SymphonyError as exc:
        logger.event("docs_sync_failed", "error", error=str(exc), code=getattr(exc, "code", None))
        return 2
    except Exception as exc:
        logger.event("docs_sync_failed", "error", error=str(exc), code="unhandled")
        return 1


def _iter_milestone_headings(text: str) -> list[tuple[int, str, str]]:
    result: list[tuple[int, str, str]] = []
    offset = 0
    for line in text.splitlines(keepends=True):
        stripped = line.strip()
        if stripped.startswith("### M") and ":" in stripped:
            heading = stripped.removeprefix("### ").strip()
            number, title = heading.split(":", 1)
            result.append((offset, number.strip(), title.strip()))
        offset += len(line)
    return result


def _extract_field(text: str, name: str) -> str | None:
    prefix = f"{name}:"
    for line in text.splitlines():
        stripped = line.strip()
        if stripped.startswith(prefix):
            return stripped[len(prefix) :].strip()
    return None


def _find_milestone_section(text: str, number: str, title: str) -> tuple[int, int] | None:
    headings = _iter_milestone_headings(text)
    for index, (start, current_number, current_title) in enumerate(headings):
        if current_number == number and current_title == title:
            end = _milestone_section_end(text, start, headings[index + 1][0] if index + 1 < len(headings) else len(text))
            return start, end
    return None


def _milestone_section_end(text: str, start: int, fallback: int) -> int:
    offset = start
    for line in text[start:].splitlines(keepends=True):
        if offset > start and line.startswith("## "):
            return min(offset, fallback)
        if offset >= fallback:
            return fallback
        offset += len(line)
    return fallback


def _replace_status_line(text: str, status: str) -> str:
    lines = text.splitlines(keepends=True)
    for index, line in enumerate(lines):
        if line.strip().startswith("Status:"):
            ending = "\r\n" if line.endswith("\r\n") else "\n" if line.endswith("\n") else ""
            lines[index] = f"Status: {status}{ending}"
            break
    return "".join(lines)


def _escape_table(value: str) -> str:
    return value.replace("|", "\\|").replace("\n", " ")


if __name__ == "__main__":
    raise SystemExit(main())
