export const apiReplacementPlan = [
  ['fetchCatalog', 'viewerService.loadInitialCatalog', 'Phase 3 compact browser catalog'],
  ['fetchInitialModel', 'viewerService.loadInitialModel', 'Phase 2 empty static startup until a user selects files'],
  ['fetchDecodeProgress', 'worker progress messages', 'Phase 1 and Phase 3 worker progress channel'],
  ['fetchPortPromotionPackets', 'viewerService.loadPortPromotionPackets', 'Out of hosted static scope until packets are committed data'],
  ['uploadModel', 'viewerService.decodeModelFile', 'Phase 1 worker-backed local file decode'],
  ['loadPath', 'removed', 'Phase 2 removes typed local server paths'],
  ['buildCatalog', 'viewerService.buildCatalogFromFiles', 'Phase 2 browser file and folder selection'],
  ['searchCatalog', 'viewerService.searchCatalog', 'Phase 3 local catalog index query'],
  ['loadCatalogAssetDetail', 'viewerService.loadCatalogAssetDetail', 'Phase 3 local detail lookup'],
  ['pickCatalogFolder', 'browser folder input', 'Phase 2 browser-owned selection'],
  ['pickCatalogFiles', 'browser multi-file input', 'Phase 2 browser-owned selection'],
  ['loadCatalogAsset', 'viewerService.loadCatalogAsset', 'Phase 4 worker/session payload loading'],
  ['loadCatalogGraphSelection', 'viewerService.loadCatalogGraphSelection', 'Phase 3 graph projection query'],
  ['loadCatalogGraphCompatible', 'viewerService.loadCatalogGraphCompatible', 'Phase 3 graph compatibility query'],
  ['resolveRuntimeSprite', 'viewerService.resolveRuntimeSprite', 'Phase 3 browser runtime resolver'],
  ['loadAssetEntityWorkflow', 'viewerService.loadAssetEntityWorkflow', 'Phase 3 entity workflow builder'],
  ['loadSceneObjectEntityWorkflow', 'viewerService.loadSceneObjectEntityWorkflow', 'Phase 3 entity workflow builder'],
  ['loadRuntimeSpriteEntityWorkflow', 'viewerService.loadRuntimeSpriteEntityWorkflow', 'Phase 3 entity workflow builder'],
  ['exportCatalogAsset', 'viewerService.exportCatalogAsset', 'Phase 6 browser download export'],
  ['catalogAudioUrl', 'viewerService.catalogAudioUrl', 'Phase 4 object URL audio'],
  ['poseAnimation', 'viewerService.poseAnimation', 'Phase 5 worker-backed animation pose'],
  ['loadAnimationSequence', 'viewerService.loadAnimationSequence', 'Phase 5 worker-backed sequence cache'],
] as const;
